# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
# SPDX-FileCopyrightText: 2019 The SourceHut API Contributors
#
# SPDX-License-Identifier: BSD-2-Clause

image: debian/stable

packages:
  - golang

sources:
  - https://git.sr.ht/~wombelix/terraform-provider-sourcehut/
  - https://git.sr.ht/~wombelix/build-helper-scripts

secrets:
  - 5b076ab5-1361-4d71-905b-4ff8c836c62c

environment:
  GIT_MIRROR_SSH_KEY: ~/.ssh/5b076ab5-1361-4d71-905b-4ff8c836c62c
  GIT_MIRROR_GITHUB: git@github.com:wombelix/terraform-provider-sourcehut.git
  GIT_MIRROR_GITLAB: git@gitlab.com:wombelix/terraform-provider-sourcehut.git
  GIT_MIRROR_CODEBERG: git@codeberg.org:wombelix/terraform-provider-sourcehut.git
  GO111MODULE: 'on'

tasks:
  - mirror: |
      cd build-helper-scripts
      source git-mirror.sh
      cd ..

      cd terraform-provider-sourcehut

      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_GITHUB"
      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_GITLAB"
      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_CODEBERG"

  - setup: |
      cd terraform-provider-sourcehut/
      go version
      go env
      #go get -u golang.org/x/lint/golint
      #go get -u github.com/securego/gosec/cmd/gosec

  - test: |
      cd terraform-provider-sourcehut/
      go test -v ./...

  - lint: |
      cd terraform-provider-sourcehut/
      #`go env GOPATH`/bin/golint -set_exit_status ./...

  - vet: |
      cd terraform-provider-sourcehut/
      go vet ./...

  - fmt: |
      cd terraform-provider-sourcehut/
      gofmt -s -l . && [ -z "$(gofmt -s -l .)" ]

  - gosec: |
      cd terraform-provider-sourcehut/
      #`go env GOPATH`/bin/gosec ./...

  - build: |
      cd terraform-provider-sourcehut/
      make

triggers:
  - action: email
    condition: failure
    to: dominik@wombacher.cc